apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hanna-bot
spec:
  selector:
    matchLabels:
      app: hanna-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: hanna-bot
    spec:
      containers:
        - image: 191518685251.dkr.ecr.us-west-1.amazonaws.com/hanna-bot:latest
          imagePullPolicy: Always
          name: hanna-bot
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hanna-bot-service
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: hanna-bot
